version: '3.8'

services:
  pomodoro-optimizer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    env_file:
      - .env
    volumes:
      # 開発時のホットリロード用
      - ./app:/code/app
    restart: unless-stopped
    container_name: pomodoro-optimizer
