[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.14",
    "scikit-learn>=1.7.0",
    "scikit-optimize>=0.10.2",
    "torch>=2.9.0",
    "uvicorn>=0.35.0",
]

[tool.ruff]
exclude = [
    # Legacy Apps
    "app/_optimize_round_from_csv_data.py",
    "app/_optimize_round_from_dynamodb_data.py",
    "app/_optimize_round_from_dynamodb_data_with_focus_score_prediction.py",
    "app/_optimize_session_from_csv_data.py",
    "app/_optimize_session_from_dynamodb_data.py",
    # Legacy Models
    "model/_old_focus_score_model.py",
    # Legacy Tests
    "test/_test_csv_handler.py",
    "test/_test_dynamodb_handler.py",
    # Handler
    "handler/_csv/",
    "handler/_dynamodb/"
]

[tool.ty.src]
exclude = [
    # Legacy Apps
    "app/_optimize_round_from_csv_data.py",
    "app/_optimize_round_from_dynamodb_data.py",
    "app/_optimize_round_from_dynamodb_data_with_focus_score_prediction.py",
    "app/_optimize_session_from_csv_data.py",
    "app/_optimize_session_from_dynamodb_data.py",
    # Legacy Models
    "model/_old_focus_score_model.py",
    # Legacy Tests
    "test/_test_csv_handler.py",
    "test/_test_dynamodb_handler.py",
    # Handler
    "handler/_csv/",
    "handler/_dynamodb/"
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["test"]
filterwarnings = [
  "ignore::DeprecationWarning:botocore"
]
ignore_glob = "_*" # Legacy Tests
